version: '3.1'

services:
  SceneTextOCRPythonAPI:
    image: docker.pkg.github.com/benjamintrapani/scenetextocr/scene_text_ocr_built:latest
    command: /bin/bash -c "cd /home/SceneTextOCR/TextTranscriptionCode/PythonRESTService/ && python3 OCRService.py 63264"
    volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "63264:63264"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

